name: CI

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
  pull_request:
    types: [opened, closed]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]
  push:
    branches:
      - main
      - master
  fork:
  gollum:

jobs:
  store_event:
    name: store_event
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: run store event
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          FS_KEY: ${{secrets.FS_KEY}}
        run: |
          pip install -r python/requirements.txt
          python -u python/store_event.py
