name: CI

on:
  issues:
    types: [opened, assigned]
  pull_request:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]
  push:
    branches:
      - main
  fork:
  gollum:
  issue_comment:
    types: [created]
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  store_event:
    name: store_event
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: run store event
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
          python data/store_event.py

          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "action issue"
          git push

  updater:
    if: always()
    needs: [store_event]
    name: updater
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: run updater
        run: |
          echo "${{ github.event_name }}"
          python data/updater.py

          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git pull
          git add -A
          git commit -m "action issue"
          git push
